/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as DraftSlugRouteImport } from './routes/draft.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftSlugRoute = DraftSlugRouteImport.update({
  id: '/draft/$slug',
  path: '/draft/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/models': typeof ModelsRoute
  '/outreach': typeof OutreachRoute
  '/draft/$slug': typeof DraftSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/models': typeof ModelsRoute
  '/outreach': typeof OutreachRoute
  '/draft/$slug': typeof DraftSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/models': typeof ModelsRoute
  '/outreach': typeof OutreachRoute
  '/draft/$slug': typeof DraftSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/audit'
    | '/batch'
    | '/history'
    | '/library'
    | '/models'
    | '/outreach'
    | '/draft/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/audit'
    | '/batch'
    | '/history'
    | '/library'
    | '/models'
    | '/outreach'
    | '/draft/$slug'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/audit'
    | '/batch'
    | '/history'
    | '/library'
    | '/models'
    | '/outreach'
    | '/draft/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AuditRoute: typeof AuditRoute
  BatchRoute: typeof BatchRoute
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  ModelsRoute: typeof ModelsRoute
  OutreachRoute: typeof OutreachRoute
  DraftSlugRoute: typeof DraftSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$slug': {
      id: '/draft/$slug'
      path: '/draft/$slug'
      fullPath: '/draft/$slug'
      preLoaderRoute: typeof DraftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AuditRoute: AuditRoute,
  BatchRoute: BatchRoute,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  ModelsRoute: ModelsRoute,
  OutreachRoute: OutreachRoute,
  DraftSlugRoute: DraftSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
